"""Writes index.html from film.json: scene sub-compositions back to back on the bar grid, the music bed and
the SFX cue sheet (real data-duration per cue, greedy track lanes so no two overlapping cues share a track).
Run from the project root:  python <skill>/scripts/assemble.py     Never hand-edit index.html."""
import os, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from film import ROOT, load, cue_time

f = load()
W, H, TOTAL, S = f['width'], f['height'], f['total'], f['starts']
missing = [s['id'] for s in f['scene_list'] if not os.path.exists(os.path.join(ROOT, 'compositions', s['id'] + '.html'))]
if missing:
    print('warning: no composition yet for', ', '.join(missing))

hosts = '\n'.join(
    f'      <div id="{s["id"]}" data-composition-id="{s["id"]}" data-composition-src="compositions/{s["id"]}.html" '
    f'data-start="{s["start"]}" data-duration="{s["dur"]}" data-track-index="1" data-width="{W}" data-height="{H}"></div>'
    for s in f['scene_list'])

sfx = f.get('sfx', {})
def probe(name):
    out = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0',
                          os.path.join(ROOT, 'assets', 'audio', 'sfx', name)], capture_output=True, text=True).stdout
    if not out.strip():
        sys.exit(f'cannot read assets/audio/sfx/{name}')
    return round(float(out.strip()), 3)
DUR = {file: probe(file) for file, _ in sfx.values()}

cues = []  # (global time, name, volume)
for c in f.get('cues', []):
    sid, expr, name = c[0], c[1], c[2]
    vol = c[3] if len(c) > 3 and c[3] is not None else sfx[name][1]
    ks = range(c[4][0], c[4][1] + 1) if len(c) > 4 else [None]
    if sid not in S:
        sys.exit(f'cue for unknown scene {sid}')
    for k in ks:
        cues.append((round(S[sid]['start'] + cue_time(expr, f, k), 3), name, vol))

lanes, aud = [], []
for g, name, vol in sorted(cues):
    if g >= TOTAL - 0.05:
        continue
    file = sfx[name][0]
    d = min(DUR[file], round(TOTAL - g, 3))
    lane = next((i for i, end in enumerate(lanes) if end <= g), None)
    if lane is None:
        lanes.append(0); lane = len(lanes) - 1
    lanes[lane] = g + d + 0.01
    aud.append(f'      <audio id="sfx-{len(aud) + 1:02d}-{name}" src="assets/audio/sfx/{file}" data-start="{g}" '
               f'data-duration="{d}" data-track-index="{11 + lane}" data-volume="{vol}"></audio>')

bgm = f.get('bgm')
bgm_tag = (f'      <audio id="bgm" src="{bgm["src"]}" data-start="0" data-duration="{TOTAL}" data-track-index="10" '
           f'data-volume="{bgm.get("volume", 0.6)}"></audio>\n') if bgm else ''
# narrated films: extra audio (the voiceover) and full-film overlay layers (a presenter) - both optional
extra_audio = ''.join(
    f'      <audio id="{a["id"]}" src="{a["src"]}" data-start="{a.get("start", 0)}" '
    f'data-duration="{a.get("dur", TOTAL)}" data-track-index="{a.get("track", 9)}" data-volume="{a.get("volume", 1)}"></audio>\n'
    for a in f.get('audio', []))
overlays = ''.join(
    f'      <div id="{o["id"]}" data-composition-id="{o["id"]}" data-composition-src="compositions/{o["id"]}.html" '
    f'data-start="{o.get("start", 0)}" data-duration="{o.get("dur", TOTAL)}" data-track-index="{o.get("track", 2)}" '
    f'data-width="{W}" data-height="{H}" style="z-index:{o.get("z", 5)}"></div>\n'
    for o in f.get('overlays', []))
G = f.get('ground', '#000000')
html = f'''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width={W}, height={H}" />
    <!-- Generated by bo-spatial-film/scripts/assemble.py from film.json - edit film.json, not this file. -->
    <script src="https://cdn.jsdelivr.net/npm/gsap@{f["gsap"]}/dist/gsap.min.js"></script>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ margin: 0; width: {W}px; height: {H}px; overflow: hidden; background: {G}; }}
      #root {{ position: relative; width: 100%; height: 100%; overflow: hidden; background: {G}; }}
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="{TOTAL}" data-width="{W}" data-height="{H}">
{hosts}
{overlays}{extra_audio}{bgm_tag}{chr(10).join(aud)}
    </div>
    <script>
      const tl = gsap.timeline({{ paused: true }});
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
'''
open(os.path.join(ROOT, 'index.html'), 'w', encoding='utf-8').write(html)
print(f'index.html: {len(S)} scenes, {len(aud)} sfx cues on {len(lanes)} lanes, total {TOTAL}s')
for s in f['scene_list']:
    print(f'  {s["id"]:<16} start {s["start"]:8.4f}  dur {s["dur"]:7.4f}')
