"""
Configuration package for the HydroGrow Smart Farming Simulator.
"""

from .constants import *
from .crop import *
from .environment import *
from .environment_sensor import *
from .equipment import *
from .equipment_runtime import *
from .maintenance import *
from .settings import Settings
from .irrigation import *
from .facility import *
from .nutrient_solution_domain import *
from .hvac_climate_domain import *
from .led_lighting_domain import *
from .water_recirculation_domain import *


__all__ = [
    "Settings",

    # Global Variables
    "APPLICATION_NAME",
    "APPLICATION_VERSION",
    "APPLICATION_OWNER",
    "DEFAULT_TIMEZONE",
    "ISO_8601_FORMAT",
    "SCHEMA_VERSION",
    "EVENT_SOURCE",
    "EVENT_TYPES",
    "SENSOR_TYPES",
    "ENVIRONMENTAL_SENSOR_CONFIG",
    "SENSOR_STATUS_HEALTHY",
    "SENSOR_STATUS_WARNING",
    "SENSOR_STATUS_FAILED",
    "SENSOR_HEALTHY_PROBABILITY",
    "SENSOR_WARNING_PROBABILITY",
    "SENSOR_FAILED_PROBABILITY",
    "VALID_ENVIRONMENTS",
    "VALID_LOG_LEVELS",
    "MIN_SIMULATION_INTERVAL_SECONDS",
    "MIN_TOTAL_FACILITIES",
    "MIN_EVENT_BATCH_SIZE",
    "MIN_RANDOM_SEED",
    "DAYTIME_SENSOR_ADJUSTMENTS",
    "NIGHTTIME_SENSOR_ADJUSTMENTS",
    "WEATHER_SENSOR_ADJUSTMENTS",
    "SIMULATION_START_HOUR",
    "SIMULATION_START_MINUTE",
    "EVENT_TYPE_ENVIRONMENTAL",
    "EVENT_TYPE_EQUIPMENT",

    # Environment Variables
    "DAY_START_HOUR",
    "NIGHT_START_HOUR",
    "WEATHER_TYPES",
    "WEATHER_SOLAR_ATTENUATION",
    "WEATHER_TRANSITIONS_MORNING",
    "WEATHER_TRANSITIONS_AFTERNOON",
    "WEATHER_TRANSITIONS_NIGHT",
    "DIURNAL_MIN_TEMP_HOUR",
    "DIURNAL_MAX_TEMP_HOUR",
    "WEATHER_MIN_DURATION_CYCLES",
    "WEATHER_MAX_DURATION_CYCLES",
    "ENVIRONMENTAL_VARIATION_PERCENTAGE",
    "FACILITY_ID_PREFIX",
    "ZONE_ID_PREFIX",

    # Equipment Variables
    "EQUIPMENT_ID_PREFIX",
    "DEFAULT_GROWING_ZONES_PER_FACILITY",
    "EQUIPMENT_TYPES",
    "EQUIPMENT_MANUFACTURERS",
    "EQUIPMENT_MODELS",

    # Equipment Runtime variables
    "MIN_EQUIPMENT_LOAD",
    "MAX_EQUIPMENT_LOAD",
    "MIN_FAILURE_PROBABILITY",
    "MAX_FAILURE_PROBABILITY",
    "ONLINE_FAILURE_THRESHOLD",
    "WARNING_FAILURE_THRESHOLD",
    "ERROR_FAILURE_THRESHOLD",
    "HEALTH_DEGRADATION_PER_RUNTIME_HOUR",
    "MAX_EQUIPMENT_HEALTH",
    "MIN_EQUIPMENT_HEALTH",
    "MIN_INITIAL_EQUIPMENT_HEALTH",
    "MAX_INITIAL_EQUIPMENT_HEALTH",
    "MIN_SIMULATION_CYCLE_HOURS",
    "MAX_EQUIPMENT_RUNTIME_HOURS",
    "NORMAL_OPERATING_LOAD_THRESHOLD",
    "MAX_LOAD_CHANGE_PER_CYCLE",
    "MAX_LOAD_VARIATION_PER_CYCLE",
    "MAX_LOAD_FAILURE_ADJUSTMENT",
    "HEALTHY_EQUIPMENT_THRESHOLD",
    "EQUIPMENT_LOAD_PROFILES",
    "EQUIPMENT_SENSOR_PROFILES",
    "SENSOR_POWER_HEALTH_STRESS_MULTIPLIER",
    "SENSOR_TEMPERATURE_HEALTH_STRESS_CELSIUS",
    "SENSOR_TEMPERATURE_FAILURE_STRESS_CELSIUS",
    "SENSOR_TEMPERATURE_VARIATION_CELSIUS",
    "SENSOR_VIBRATION_HEALTH_STRESS_MM_S",
    "SENSOR_VIBRATION_FAILURE_STRESS_MM_S",
    "SENSOR_VIBRATION_VARIATION_MM_S",
    "DAYTIME_DEMAND_MULTIPLIER",
    "NIGHTTIME_DEMAND_MULTIPLIER",
    "HOURS_PER_DAY",

    # Facility Variables
    "PHILIPPINE_FACILITY_PROFILES"
    "EVENT_TYPE_FACILITY",
    "HEALTHY_FACILITY_THRESHOLD",
    "ZONE_POWER_CONSUMPTION_KW",
    "ZONE_WATER_RECIRCULATION_LPH",
    # Nutrient Solution Variables
    "TARGET_NUTRIENT_PH",
    "MIN_SAFE_NUTRIENT_PH",
    "MAX_SAFE_NUTRIENT_PH",
    "TARGET_NUTRIENT_EC_MS_CM",
    "MIN_SAFE_NUTRIENT_EC_MS_CM",
    "MAX_SAFE_NUTRIENT_EC_MS_CM",
    "TARGET_DISSOLVED_OXYGEN_MG_L",
    "MIN_SAFE_DISSOLVED_OXYGEN_MG_L",
    "MAX_SAFE_DISSOLVED_OXYGEN_MG_L",
    "NUTRIENT_DOSING_RATE_ML_PER_SEC",
    "PH_ADJUST_DOSING_RATE_ML_PER_SEC",
    # HVAC Climate Variables
    "TARGET_AIR_TEMPERATURE_CELSIUS",
    "MIN_SAFE_AIR_TEMPERATURE_CELSIUS",
    "MAX_SAFE_AIR_TEMPERATURE_CELSIUS",
    "TARGET_RELATIVE_HUMIDITY_PERCENT",
    "MIN_SAFE_RELATIVE_HUMIDITY_PERCENT",
    "MAX_SAFE_RELATIVE_HUMIDITY_PERCENT",
    "TARGET_CO2_PPM",
    "MIN_SAFE_CO2_PPM",
    "MAX_SAFE_CO2_PPM",
    "DEFAULT_HVAC_AIRFLOW_CFM",
    # LED Lighting Variables
    "TARGET_PPFD_UMOL_M2_S",
    "MIN_PPFD_UMOL_M2_S",
    "MAX_PPFD_UMOL_M2_S",
    "TARGET_DLI_MOL_M2_DAY",
    "MIN_DLI_MOL_M2_DAY",
    "MAX_DLI_MOL_M2_DAY",
    "DEFAULT_PHOTOPERIOD_HOURS",
    # Water Recirculation Variables
    "DEFAULT_RESERVOIR_CAPACITY_LITERS",
    "MIN_RESERVOIR_WATER_LEVEL_PERCENT",
    "DEFAULT_PUMP_FLOW_RATE_GPM",
    "MIN_SAFE_PUMP_FLOW_RATE_GPM",
    "MAX_SAFE_PUMP_FLOW_RATE_GPM",
    "TARGET_PUMP_PRESSURE_PSI",
    "MIN_SAFE_PUMP_PRESSURE_PSI",
    "MAX_SAFE_PUMP_PRESSURE_PSI",
    "TARGET_CHILLER_WATER_TEMP_CELSIUS",

    # Maintenance 
    "EVENT_TYPE_MAINTENANCE",
    "WORK_ORDER_ID_PREFIX",
    "TECHNICIAN_ID_PREFIX",
    "MAINTENANCE_TYPE_PREVENTIVE",
    "MAINTENANCE_TYPE_CORRECTIVE",
    "MAINTENANCE_TYPE_EMERGENCY",
    "MAINTENANCE_TYPE_INSPECTION",
    "MAINTENANCE_TYPES",
    "MAINTENANCE_PRIORITY_LOW",
    "MAINTENANCE_PRIORITY_MEDIUM",
    "MAINTENANCE_PRIORITY_HIGH",
    "MAINTENANCE_PRIORITY_CRITICAL",
    "MAINTENANCE_PRIORITIES",
    "WORK_STATUS_OPEN",
    "WORK_STATUS_ASSIGNED",
    "WORK_STATUS_IN_PROGRESS",
    "WORK_STATUS_COMPLETED",
    "WORK_STATUS_CANCELLED",
    "WORK_STATUSES",
    "DEFAULT_PREVENTIVE_DURATION_MINUTES",
    "DEFAULT_CORRECTIVE_DURATION_MINUTES",
    "DEFAULT_INSPECTION_DURATION_MINUTES",
    "DEFAULT_EMERGENCY_DURATION_MINUTES",
    "DEFAULT_TECHNICIANS",
    "MAINTENANCE_INTERVAL_HOURS",
    "MAINTENANCE_HEALTH_THRESHOLD",
    "MAINTENANCE_RESTORE_HEALTH",
    "MAINTENANCE_RESET_FAILURE_PROBABILITY",

    # Crop variables
    "CROP_GROWTH_PROFILES",
    "CROP_STAGE_GERMINATION",
    "CROP_STAGE_SEEDLING",
    "CROP_STAGE_VEGETATIVE",
    "CROP_STAGE_MATURE",
    "CROP_STAGE_HARVESTED",
    "CROP_LIFECYCLE_STAGES",
    "NEXT_CROP_STAGE",
    "EVENT_TYPE_CROP_LIFECYCLE",
    "MAX_HEALTH_SCORE",
    "IDEAL_GROWTH_TEMPERATURE_C",
    "IDEAL_GROWTH_HUMIDITY_PERCENT",
    "TEMPERATURE_GROWTH_TOLERANCE_C",
    "HUMIDITY_GROWTH_TOLERANCE_PERCENT",
    "BIOMASS_GROWTH_MULTIPLIER",
    "WATER_UPTAKE_PER_GRAM_BIOMASS",
    "AIR_TEMPERATURE_VARIATION_C",
    "HUMIDITY_VARIATION_PERCENT",
    "WATER_PH_VARIATION",
    "EC_VARIATION",

    # Irrigation Variables

    "DEFAULT_IRRIGATION_INTERVAL_CYCLES",
    "DEFAULT_IRRIGATION_DURATION_CYCLES",
    "DEFAULT_IRRIGATION_FLOW_RATE_LPM",
    "DEFAULT_IRRIGATION_PRESSURE_BAR",
    "DEFAULT_WATER_APPLICATION_LITERS",
    "IRRIGATION_CONTROLLER_UPDATE_INTERVAL",

    # Transferable to environment later
    "DEFAULT_WATER_PH",
    "DEFAULT_ELECTRICAL_CONDUCTIVITY",
    "DEFAULT_AIR_TEMPERATURE_C",
    "DEFAULT_RELATIVE_HUMIDITY_PERCENT",
    
    # Environmental Variables
    "SensorMetadata",
    "FacilityId",
    "WeatherType",
]