"""
Environmental & Ambient Weather Configuration.

This module contains constants for the simulation clock, diurnal timecycles,
tropical weather states, and Markov weather state transition matrices.
"""

from typing import Final
from .constants import WeatherType

# ========================================================================================
# Environmental Simulation
# ========================================================================================

DAY_START_HOUR: Final[int] = 6
NIGHT_START_HOUR: Final[int] = 18

ENVIRONMENTAL_VARIATION_PERCENTAGE: Final[float] = 0.20

# ========================================================================================
# Weather Simulation
# ========================================================================================

WEATHER_SUNNY: Final[str] = "SUNNY"
WEATHER_PARTLY_CLOUDY: Final[str] = "PARTLY_CLOUDY"
WEATHER_CLOUDY: Final[str] = "CLOUDY"
WEATHER_RAINY: Final[str] = "RAINY"
WEATHER_THUNDERSTORM: Final[str] = "THUNDERSTORM"
WEATHER_FOGGY: Final[str] = "FOGGY"

WEATHER_TYPES: Final[tuple[WeatherType, ...]] = (
    WEATHER_SUNNY,
    WEATHER_PARTLY_CLOUDY,
    WEATHER_CLOUDY,
    WEATHER_RAINY,
    WEATHER_THUNDERSTORM,
    WEATHER_FOGGY,
)

# Diurnal Ambient Temperature Fluctuation Constants
DIURNAL_MIN_TEMP_HOUR: Final[float] = 5.5   # Coldest hour of dawn
DIURNAL_MAX_TEMP_HOUR: Final[float] = 13.5  # Hottest hour of afternoon

# Solar Irradiance Attenuation Factors per Weather State
WEATHER_SOLAR_ATTENUATION: Final[dict[WeatherType, float]] = {
    WEATHER_SUNNY: 1.00,
    WEATHER_PARTLY_CLOUDY: 0.70,
    WEATHER_CLOUDY: 0.35,
    WEATHER_RAINY: 0.20,
    WEATHER_THUNDERSTORM: 0.10,
    WEATHER_FOGGY: 0.25,
}

# Markov Transition Probability Matrix by Time Period
# format: { current_state: { next_state: probability } }
WEATHER_TRANSITIONS_MORNING: Final[dict[WeatherType, dict[WeatherType, float]]] = {
    WEATHER_SUNNY: {WEATHER_SUNNY: 0.60, WEATHER_PARTLY_CLOUDY: 0.30, WEATHER_CLOUDY: 0.10, WEATHER_RAINY: 0.00, WEATHER_THUNDERSTORM: 0.00, WEATHER_FOGGY: 0.00},
    WEATHER_PARTLY_CLOUDY: {WEATHER_SUNNY: 0.40, WEATHER_PARTLY_CLOUDY: 0.45, WEATHER_CLOUDY: 0.15, WEATHER_RAINY: 0.00, WEATHER_THUNDERSTORM: 0.00, WEATHER_FOGGY: 0.00},
    WEATHER_CLOUDY: {WEATHER_SUNNY: 0.20, WEATHER_PARTLY_CLOUDY: 0.30, WEATHER_CLOUDY: 0.40, WEATHER_RAINY: 0.10, WEATHER_THUNDERSTORM: 0.00, WEATHER_FOGGY: 0.00},
    WEATHER_RAINY: {WEATHER_SUNNY: 0.00, WEATHER_PARTLY_CLOUDY: 0.15, WEATHER_CLOUDY: 0.35, WEATHER_RAINY: 0.40, WEATHER_THUNDERSTORM: 0.10, WEATHER_FOGGY: 0.00},
    WEATHER_THUNDERSTORM: {WEATHER_SUNNY: 0.00, WEATHER_PARTLY_CLOUDY: 0.00, WEATHER_CLOUDY: 0.30, WEATHER_RAINY: 0.40, WEATHER_THUNDERSTORM: 0.30, WEATHER_FOGGY: 0.00},
    WEATHER_FOGGY: {WEATHER_SUNNY: 0.30, WEATHER_PARTLY_CLOUDY: 0.30, WEATHER_CLOUDY: 0.20, WEATHER_RAINY: 0.00, WEATHER_THUNDERSTORM: 0.00, WEATHER_FOGGY: 0.20},
}

WEATHER_TRANSITIONS_AFTERNOON: Final[dict[WeatherType, dict[WeatherType, float]]] = {
    WEATHER_SUNNY: {WEATHER_SUNNY: 0.40, WEATHER_PARTLY_CLOUDY: 0.40, WEATHER_CLOUDY: 0.15, WEATHER_RAINY: 0.05, WEATHER_THUNDERSTORM: 0.00, WEATHER_FOGGY: 0.00},
    WEATHER_PARTLY_CLOUDY: {WEATHER_SUNNY: 0.20, WEATHER_PARTLY_CLOUDY: 0.40, WEATHER_CLOUDY: 0.25, WEATHER_RAINY: 0.10, WEATHER_THUNDERSTORM: 0.05, WEATHER_FOGGY: 0.00},
    WEATHER_CLOUDY: {WEATHER_SUNNY: 0.05, WEATHER_PARTLY_CLOUDY: 0.20, WEATHER_CLOUDY: 0.40, WEATHER_RAINY: 0.20, WEATHER_THUNDERSTORM: 0.15, WEATHER_FOGGY: 0.00},
    WEATHER_RAINY: {WEATHER_SUNNY: 0.00, WEATHER_PARTLY_CLOUDY: 0.10, WEATHER_CLOUDY: 0.30, WEATHER_RAINY: 0.40, WEATHER_THUNDERSTORM: 0.20, WEATHER_FOGGY: 0.00},
    WEATHER_THUNDERSTORM: {WEATHER_SUNNY: 0.00, WEATHER_PARTLY_CLOUDY: 0.05, WEATHER_CLOUDY: 0.25, WEATHER_RAINY: 0.35, WEATHER_THUNDERSTORM: 0.35, WEATHER_FOGGY: 0.00},
    WEATHER_FOGGY: {WEATHER_SUNNY: 0.40, WEATHER_PARTLY_CLOUDY: 0.30, WEATHER_CLOUDY: 0.30, WEATHER_RAINY: 0.00, WEATHER_THUNDERSTORM: 0.00, WEATHER_FOGGY: 0.00},
}

WEATHER_TRANSITIONS_NIGHT: Final[dict[WeatherType, dict[WeatherType, float]]] = {
    WEATHER_SUNNY: {WEATHER_SUNNY: 0.50, WEATHER_PARTLY_CLOUDY: 0.30, WEATHER_CLOUDY: 0.10, WEATHER_RAINY: 0.00, WEATHER_THUNDERSTORM: 0.00, WEATHER_FOGGY: 0.10},
    WEATHER_PARTLY_CLOUDY: {WEATHER_SUNNY: 0.30, WEATHER_PARTLY_CLOUDY: 0.40, WEATHER_CLOUDY: 0.15, WEATHER_RAINY: 0.05, WEATHER_THUNDERSTORM: 0.00, WEATHER_FOGGY: 0.10},
    WEATHER_CLOUDY: {WEATHER_SUNNY: 0.10, WEATHER_PARTLY_CLOUDY: 0.20, WEATHER_CLOUDY: 0.40, WEATHER_RAINY: 0.15, WEATHER_THUNDERSTORM: 0.05, WEATHER_FOGGY: 0.10},
    WEATHER_RAINY: {WEATHER_SUNNY: 0.00, WEATHER_PARTLY_CLOUDY: 0.10, WEATHER_CLOUDY: 0.30, WEATHER_RAINY: 0.40, WEATHER_THUNDERSTORM: 0.10, WEATHER_FOGGY: 0.10},
    WEATHER_THUNDERSTORM: {WEATHER_SUNNY: 0.00, WEATHER_PARTLY_CLOUDY: 0.05, WEATHER_CLOUDY: 0.25, WEATHER_RAINY: 0.40, WEATHER_THUNDERSTORM: 0.25, WEATHER_FOGGY: 0.05},
    WEATHER_FOGGY: {WEATHER_SUNNY: 0.20, WEATHER_PARTLY_CLOUDY: 0.20, WEATHER_CLOUDY: 0.20, WEATHER_RAINY: 0.05, WEATHER_THUNDERSTORM: 0.00, WEATHER_FOGGY: 0.35},
}

WEATHER_MIN_DURATION_CYCLES: Final[int] = 2
WEATHER_MAX_DURATION_CYCLES: Final[int] = 6

# ========================================================================================
# Facility Configuration
# ========================================================================================

FACILITY_ID_PREFIX: Final[str] = "FAC"

ZONE_ID_PREFIX: Final[str] = "ZONE"
