"""
Facility Domain Configuration - Hydroponics Vertical Farming.

This module contains hardcoded configuration data and regional profiles
for all 8 hydroponics vertical farming facilities in the Philippines (FAC-001 to FAC-008).
"""

from typing import Final
from smart_farming.schemas import FacilityProfile, ZoneMicroLocation


# ========================================================================================
# Philippine Regional Hydroponics Vertical Farming Profiles Registry
# ========================================================================================

PHILIPPINE_FACILITY_PROFILES: Final[dict[str, FacilityProfile]] = {
    "FAC-001": FacilityProfile(
        facility_id="FAC-001",
        facility_name="Benguet Highland Strawberries Vertical Farm",
        location="La Trinidad, Benguet",
        region="Cordillera Administrative Region (CAR)",
        domain_focus="6-Tier Vertical Racks (Strawberries & Kale)",
        target_temperature_celsius=18.0,
        target_humidity_percent=75.0,
        target_ph=5.80,
        target_ec=1.80,
        primary_crops=("Alpine Strawberries", "Butterhead Lettuce", "Kale"),
        operating_hours="05:00 - 21:00 PHT",
        anomaly_trait="Mountain power dips, water level duplicate bursts (~3%)",
        latitude=16.4550,
        longitude=120.5875,
        elevation_m=1500.0,
        water_source="Mountain Spring & Rain Harvesting",
        power_grid_redundancy="Dual Feed + 250kVA Diesel GenSet",
        max_zone_capacity=12,
        micro_locations=(
            ZoneMicroLocation("ZONE-001", "Top-Tier Highland LED Canopy", "strawberry"),
            ZoneMicroLocation("ZONE-002", "Mid-Tier NFT Rack Alpha", "butterhead_lettuce"),
            ZoneMicroLocation("ZONE-003", "Lower-Tier High-Humidity Bed", "kale"),
            ZoneMicroLocation("ZONE-004", "Highland Nursery Racks", "strawberry"),
        ),
    ),
    "FAC-002": FacilityProfile(
        facility_id="FAC-002",
        facility_name="Tagaytay Ridge Hydroponics Nursery",
        location="Tagaytay City, Cavite",
        region="CALABARZON (Region IV-A)",
        domain_focus="4-Tier Ridge Modules (Basil & Arugula)",
        target_temperature_celsius=22.0,
        target_humidity_percent=70.0,
        target_ph=6.00,
        target_ec=1.70,
        primary_crops=("Genovese Basil", "Batavia Lettuce", "Arugula"),
        operating_hours="06:00 - 22:00 PHT",
        anomaly_trait="Condensation humidity drift, empty payload strings ('')",
        latitude=14.1153,
        longitude=120.9621,
        elevation_m=610.0,
        water_source="Deep Well & Recirculating RO",
        power_grid_redundancy="Meralco Grid + Solar PV Backup",
        max_zone_capacity=8,
        micro_locations=(
            ZoneMicroLocation("ZONE-001", "Ridge Micro-Climate Nursery Chamber", "basil"),
            ZoneMicroLocation("ZONE-002", "Vertical NFT Rack Beta", "batavia_lettuce"),
            ZoneMicroLocation("ZONE-003", "Controlled Herb Tier", "arugula"),
            ZoneMicroLocation("ZONE-004", "Ridge Propagation Line 1", "basil"),
            ZoneMicroLocation("ZONE-005", "Ridge Propagation Line 2", "batavia_lettuce"),
        ),
    ),
    "FAC-003": FacilityProfile(
        facility_id="FAC-003",
        facility_name="Metro Manila Rooftop Vertical Hydro-Farm",
        location="Bonifacio Global City (BGC), Taguig City",
        region="National Capital Region (NCR)",
        domain_focus="8-Tier Plant Factory (Romaine & Microgreens)",
        target_temperature_celsius=23.0,
        target_humidity_percent=65.0,
        target_ph=6.00,
        target_ec=1.85,
        primary_crops=("Romaine Lettuce", "Microgreens", "Wheatgrass"),
        operating_hours="06:00 - 22:00 PHT",
        anomaly_trait="Urban HVAC thermal overload spikes (temperature = 9999.99)",
        latitude=14.5547,
        longitude=121.0509,
        elevation_m=35.0,
        water_source="Municipal Utility + Commercial 3-Stage RO",
        power_grid_redundancy="Meralco Dual Substation + UPS Battery Bank",
        max_zone_capacity=16,
        micro_locations=(
            ZoneMicroLocation("ZONE-001", "Top-Tier High PPFD Canopy", "butterhead_lettuce"),
            ZoneMicroLocation("ZONE-002", "BGC Urban Microgreen Chamber", "microgreens"),
            ZoneMicroLocation("ZONE-003", "NFT High-Density Rack", "spinach"),
            ZoneMicroLocation("ZONE-004", "BGC Rooftop Tier 4", "romaine"),
            ZoneMicroLocation("ZONE-005", "BGC Rooftop Tier 5", "microgreens"),
            ZoneMicroLocation("ZONE-006", "BGC Rooftop Tier 6", "wheatgrass"),
        ),
    ),
    "FAC-004": FacilityProfile(
        facility_id="FAC-004",
        facility_name="Davao City Indoor Greens Vertical Facility",
        location="Davao City, Davao del Sur",
        region="Davao Region (Region XI)",
        domain_focus="10-Tier Hydro Towers (Pak Choy & Spinach)",
        target_temperature_celsius=25.0,
        target_humidity_percent=75.0,
        target_ph=6.10,
        target_ec=1.90,
        primary_crops=("Pak Choy", "Spinach", "Asian Baby Greens"),
        operating_hours="05:30 - 21:30 PHT",
        anomaly_trait="pH sensor probe calibration sub-zero reading (-999.0)",
        latitude=7.1907,
        longitude=125.4553,
        elevation_m=22.0,
        water_source="River Intake & Automated DWC Filtration",
        power_grid_redundancy="DLPC Grid + Biogas & Diesel Backup",
        max_zone_capacity=20,
        micro_locations=(
            ZoneMicroLocation("ZONE-001", "High-Tower Aeroponic Array A", "spinach"),
            ZoneMicroLocation("ZONE-002", "Sub-Tropical Vertical Chamber", "kale"),
            ZoneMicroLocation("ZONE-003", "DWC Nutrient Tank 1", "arugula"),
            ZoneMicroLocation("ZONE-004", "Davao Tower Array B", "pak_choy"),
            ZoneMicroLocation("ZONE-005", "Davao Tower Array C", "spinach"),
            ZoneMicroLocation("ZONE-006", "Davao Tower Array D", "baby_greens"),
            ZoneMicroLocation("ZONE-007", "Davao Tower Array E", "pak_choy"),
        ),
    ),
    "FAC-005": FacilityProfile(
        facility_id="FAC-005",
        facility_name="Laguna Technopark Hydroponic Plant Factory",
        location="Calamba City, Laguna",
        region="CALABARZON (Region IV-A)",
        domain_focus="Industrial NFT/DWC Lines (Tomatoes & Herbs)",
        target_temperature_celsius=24.0,
        target_humidity_percent=68.0,
        target_ph=6.00,
        target_ec=1.80,
        primary_crops=("Cherry Tomatoes", "Sweet Basil", "Oakleaf Lettuce"),
        operating_hours="06:00 - 22:00 PHT",
        anomaly_trait="Omitted payload keys (null), lowercase casing (fac-005, online)",
        latitude=14.2117,
        longitude=121.1653,
        elevation_m=18.0,
        water_source="Laguna Lake Industrial Treated Water",
        power_grid_redundancy="Industrial Park Substation + Solar Rooftop Array",
        max_zone_capacity=24,
        micro_locations=(
            ZoneMicroLocation("ZONE-001", "Industrial DWC Vine System", "basil"),
            ZoneMicroLocation("ZONE-002", "NFT Commercial Rack Line 1", "butterhead_lettuce"),
            ZoneMicroLocation("ZONE-003", "High-Output Herb Tier", "parsley"),
            ZoneMicroLocation("ZONE-004", "Laguna Plant Factory Line 4", "cherry_tomatoes"),
            ZoneMicroLocation("ZONE-005", "Laguna Plant Factory Line 5", "sweet_basil"),
            ZoneMicroLocation("ZONE-006", "Laguna Plant Factory Line 6", "oakleaf"),
            ZoneMicroLocation("ZONE-007", "Laguna Plant Factory Line 7", "butterhead_lettuce"),
            ZoneMicroLocation("ZONE-008", "Laguna Plant Factory Line 8", "parsley"),
        ),
    ),
    "FAC-006": FacilityProfile(
        facility_id="FAC-006",
        facility_name="Cebu Urban Vertical Greens Hub",
        location="Cebu IT Park, Cebu City",
        region="Central Visayas (Region VII)",
        domain_focus="6-Tier Smart City Hydro (Lollo Rossa & Watercress)",
        target_temperature_celsius=24.5,
        target_humidity_percent=70.0,
        target_ph=6.05,
        target_ec=1.80,
        primary_crops=("Lollo Rossa Lettuce", "Cilantro", "Watercress"),
        operating_hours="05:00 - 21:00 PHT",
        anomaly_trait="Gateway network latency out-of-order timestamps (15-120 min delay)",
        latitude=10.3283,
        longitude=123.9064,
        elevation_m=15.0,
        water_source="Desalinated Municipal Water",
        power_grid_redundancy="VECO Grid + Battery Energy Storage (BESS)",
        max_zone_capacity=12,
        micro_locations=(
            ZoneMicroLocation("ZONE-001", "IT Park Smart LED Canopy", "batavia_lettuce"),
            ZoneMicroLocation("ZONE-002", "Urban Vertical NFT Rack 2", "cilantro"),
            ZoneMicroLocation("ZONE-003", "Aeroponic Herb Chamber", "arugula"),
            ZoneMicroLocation("ZONE-004", "Cebu IT Park Rack 4", "lollo_rossa"),
            ZoneMicroLocation("ZONE-005", "Cebu IT Park Rack 5", "watercress"),
            ZoneMicroLocation("ZONE-006", "Cebu IT Park Rack 6", "cilantro"),
        ),
    ),
    "FAC-007": FacilityProfile(
        facility_id="FAC-007",
        facility_name="Clark Freeport Urban Hydroponic Complex",
        location="Clark Freeport Zone, Angeles City, Pampanga",
        region="Central Luzon (Region III)",
        domain_focus="12-Tier Aeroponic Towers (Peppers & Mint)",
        target_temperature_celsius=25.0,
        target_humidity_percent=68.0,
        target_ph=6.15,
        target_ec=1.95,
        primary_crops=("Bell Peppers", "Mint", "Red Coral Lettuce"),
        operating_hours="05:00 - 21:00 PHT",
        anomaly_trait="Dual-clock microcontrollers emitting mixed timestamp formats (ISO vs. Epoch)",
        latitude=15.1804,
        longitude=120.5401,
        elevation_m=150.0,
        water_source="Aquifer Deep Well",
        power_grid_redundancy="Clark Electric Distribution + Dual GenSet",
        max_zone_capacity=30,
        micro_locations=(
            ZoneMicroLocation("ZONE-001", "High-Capacity Aeroponic Tower A", "spinach"),
            ZoneMicroLocation("ZONE-002", "Controlled Photoperiod Module", "parsley"),
            ZoneMicroLocation("ZONE-003", "NFT Leafy Greens Tier", "butterhead_lettuce"),
            ZoneMicroLocation("ZONE-004", "Clark Tower Array B", "bell_peppers"),
            ZoneMicroLocation("ZONE-005", "Clark Tower Array C", "mint"),
            ZoneMicroLocation("ZONE-006", "Clark Tower Array D", "red_coral"),
            ZoneMicroLocation("ZONE-007", "Clark Tower Array E", "spinach"),
            ZoneMicroLocation("ZONE-008", "Clark Tower Array F", "parsley"),
            ZoneMicroLocation("ZONE-009", "Clark Tower Array G", "butterhead_lettuce"),
            ZoneMicroLocation("ZONE-010", "Clark Tower Array H", "mint"),
        ),
    ),
    "FAC-008": FacilityProfile(
        facility_id="FAC-008",
        facility_name="Iloilo City Microgreens Vertical Agro-Lab",
        location="Mandurriao, Iloilo City",
        region="Western Visayas (Region VI)",
        domain_focus="5-Tier Precision LED Modules (Radish & Pea Shoots)",
        target_temperature_celsius=23.5,
        target_humidity_percent=72.0,
        target_ph=5.95,
        target_ec=1.75,
        primary_crops=("Radish Microgreens", "Sunflower Shoots", "Pea Shoots"),
        operating_hours="06:00 - 22:00 PHT",
        anomaly_trait="Serial buffer string typos (operating_status: 'ONLNE', sensor_status: 'WARNIN')",
        latitude=10.7202,
        longitude=122.5463,
        elevation_m=8.0,
        water_source="Municipal Utility + UV Sterilization Unit",
        power_grid_redundancy="MORE Power Grid + Emergency Generator",
        max_zone_capacity=10,
        micro_locations=(
            ZoneMicroLocation("ZONE-001", "Precision Microgreen Tray Module A", "microgreens"),
            ZoneMicroLocation("ZONE-002", "LED Agro-Research Chamber", "basil"),
            ZoneMicroLocation("ZONE-003", "High-Density Sprout Rack", "strawberry"),
            ZoneMicroLocation("ZONE-004", "Iloilo Tray Module B", "radish_microgreens"),
            ZoneMicroLocation("ZONE-005", "Iloilo Tray Module C", "pea_shoots"),
        ),
    ),
}

# ========================================================================================
# Facility Operational Calculation Constants
# ========================================================================================

EVENT_TYPE_FACILITY: Final[str] = "FacilityEvent"
HEALTHY_FACILITY_THRESHOLD: Final[float] = 70.0
ZONE_POWER_CONSUMPTION_KW: Final[float] = 45.5
ZONE_WATER_RECIRCULATION_LPH: Final[float] = 250.0
