"""
Utility functions for working with dates and timestamps.

All timestamps generated by the simulator use UTC to ensure consistency
across the application and downstream Microsoft Fabric components.
"""

from datetime import datetime

from smart_farming.config import (
    DEFAULT_TIMEZONE, 
    ISO_8601_FORMAT,
)


def utc_now() -> datetime:
    """
    Return the current UTC datetime.

    Returns:
        Current timezone-aware UTC datetime.
    """

    return datetime.now(DEFAULT_TIMEZONE)

def format_timestamp(timestamp: datetime) -> str:
    """
    Convert a datetime object into an ISO 8601 formatted string.

    Args:
        timestamp: Datetime object to format.
    
    Returns:
        ISO 8601 formatted timestamp.
    """

    return timestamp.strftime(ISO_8601_FORMAT)